#!/bin/sh
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


container_version() {
 # /usr/bin/podman --version |  awk -F ' ' '{print $3}'
 echo "0.0.0"
}

container_entrypoint() {
 FFDB_PATH="/mnt/volumes/container/ffdb"
 FFDB_FILE="firefly.sql"
 if [ ! -f "$FFDB_PATH/$FFDB_FILE" ] ; then
  /bin/mkdir -p $FFDB_PATH/
  /bin/touch $FFDB_PATH/$FFDB_FILE
  cd /opt/firefly
  /usr/bin/php artisan firefly-iii:upgrade-database
  /usr/bin/php artisan firefly-iii:correct-database
  /usr/bin/php artisan firefly-iii:report-integrity
  /usr/bin/php artisan passport:install --force
  /bin/chown firefly:www-data -R $FFDB_PATH
  /bin/chmod 777 -R $FFDB_PATH
 fi
 # tail -f /dev/null
 sudo /usr/sbin/php-fpm82
 sudo nginx -g "daemon off;"
}
